iOS15 specific recommended zoom factor
sourcetoad/react-native-idscan-sdk pull request #58
Opened 2023-05-04 06:32 UTC by ian-wd

2023-05-08 17:43 UTC, iBotPeaches requested changes

2023-05-08 17:43 UTC, iBotPeaches commented on ios/ScannerViewController.m
> +        if (minimumSubjectDistanceForCode < deviceMinimumFocusDistance) {
Never could get this to hit in my testing.

2023-05-09 02:02 UTC, ian-wd commented on ios/ScannerViewController.m
> +    });
same here, it fixed when I added it last time but today it shows the same error again

2023-05-09 14:41 UTC, iBotPeaches commented on ios/ScannerViewController.m
> +        [self setRecommendedZoomFactor];
Should this run at same interval with refocus? It seems if I understand this right it only runs on open, which I doubt the QR is perfectly placed at the right time to obtain a zoom factor.

2023-05-10 00:31 UTC, ian-wd commented on ios/ScannerViewController.m
> +        [self setRecommendedZoomFactor];
feels it's pretty expensive to run this along with the `reFocus` interval, maybe we should make this optional and have it integrated as a button?

2023-05-10 00:36 UTC, iBotPeaches commented on ios/ScannerViewController.m
> +        [self setRecommendedZoomFactor];
Ah maybe I misunderstood the video I watched. It seemed like this ran over n over to account for distance to object changing.

2023-05-15 12:27 UTC, iBotPeaches approved these changes

2023-05-15 12:27 UTC, merged